/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;
import ec.edu.ups.controlador.*;
import ec.edu.ups.modelo.*;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
/**
 *
 * @author Dutan2000
 */
public class MenuPrincipal extends javax.swing.JFrame {

    //vistas 
    private InicioSession inicioSession;
    private ListarUsuarios listarUsuario;
    private MenuTelefono menuTelefono;
    private MenuUsuario menuUsuario;
    private RegistrarUsuario registrarUsuario;

    
    //controlador
    private ControladorGeneral controladorGeneral;
    private ControladorUsuario1 controladorUsuario;
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        tabCerrarSession.setVisible(false);
        tabMenu.setVisible(false);
        
        controladorGeneral= new ControladorGeneral();
        controladorUsuario= new ControladorUsuario1(controladorGeneral);
        
        
        inicioSession= new InicioSession(this, controladorUsuario);
        listarUsuario=new ListarUsuarios(controladorUsuario, controladorGeneral);
        menuTelefono= new MenuTelefono(controladorGeneral, controladorUsuario);
        menuUsuario=new MenuUsuario(controladorUsuario);
        registrarUsuario=new RegistrarUsuario(controladorUsuario);
        
        desktopPane.add(inicioSession);
        desktopPane.add(listarUsuario);
        desktopPane.add(menuTelefono);
        desktopPane.add(menuUsuario);
        desktopPane.add(registrarUsuario);
        
        
    }
    
    public JMenu getTabMenu(){
        return tabMenu;
    } 
    
    public JMenuItem getIniciarSession(){
        return tabIniciarSession;
    }
    public JMenuItem getregistrarUsuario(){
        return tabRegistrarU;
    }
    public JMenuItem getCerrarSession(){
        return tabCerrarSession;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        tabInicio = new javax.swing.JMenu();
        tabIniciarSession = new javax.swing.JMenuItem();
        tabListar = new javax.swing.JMenuItem();
        tabRegistrarU = new javax.swing.JMenuItem();
        tabCerrarSession = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        tabMenu = new javax.swing.JMenu();
        tabMenuTelefono = new javax.swing.JMenuItem();
        tabMenuUsuario = new javax.swing.JMenuItem();
        tabIdiomas = new javax.swing.JMenu();
        tabIdiomaEs = new javax.swing.JMenuItem();
        tabIdiomaEN = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setLayout(null);

        tabInicio.setMnemonic('f');
        tabInicio.setText("INICIO");

        tabIniciarSession.setMnemonic('o');
        tabIniciarSession.setText("I. SESSION");
        tabIniciarSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabIniciarSessionActionPerformed(evt);
            }
        });
        tabInicio.add(tabIniciarSession);

        tabListar.setMnemonic('s');
        tabListar.setText("LISTAR");
        tabListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabListarActionPerformed(evt);
            }
        });
        tabInicio.add(tabListar);

        tabRegistrarU.setMnemonic('a');
        tabRegistrarU.setText("REGISTRAR U.");
        tabRegistrarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabRegistrarUActionPerformed(evt);
            }
        });
        tabInicio.add(tabRegistrarU);

        tabCerrarSession.setMnemonic('a');
        tabCerrarSession.setText("CERRAR SESSION");
        tabCerrarSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabCerrarSessionActionPerformed(evt);
            }
        });
        tabInicio.add(tabCerrarSession);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("EXIT");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        tabInicio.add(exitMenuItem);

        menuBar.add(tabInicio);

        tabMenu.setMnemonic('e');
        tabMenu.setText("MENU");

        tabMenuTelefono.setMnemonic('t');
        tabMenuTelefono.setText("TELEFONOS");
        tabMenuTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabMenuTelefonoActionPerformed(evt);
            }
        });
        tabMenu.add(tabMenuTelefono);

        tabMenuUsuario.setMnemonic('y');
        tabMenuUsuario.setText("USUARIO");
        tabMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabMenuUsuarioActionPerformed(evt);
            }
        });
        tabMenu.add(tabMenuUsuario);

        menuBar.add(tabMenu);

        tabIdiomas.setMnemonic('h');
        tabIdiomas.setText("IDIOMA");

        tabIdiomaEs.setMnemonic('c');
        tabIdiomaEs.setText("ESPAÑOL");
        tabIdiomaEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabIdiomaEsActionPerformed(evt);
            }
        });
        tabIdiomas.add(tabIdiomaEs);

        tabIdiomaEN.setMnemonic('a');
        tabIdiomaEN.setText("INGLES");
        tabIdiomaEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabIdiomaENActionPerformed(evt);
            }
        });
        tabIdiomas.add(tabIdiomaEN);

        menuBar.add(tabIdiomas);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void tabRegistrarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabRegistrarUActionPerformed

        registrarUsuario.setVisible(true);

    }//GEN-LAST:event_tabRegistrarUActionPerformed

    private void tabIdiomaENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabIdiomaENActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabIdiomaENActionPerformed

    private void tabCerrarSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabCerrarSessionActionPerformed
        tabMenu.setVisible(false);
        tabCerrarSession.setVisible(false);
        tabIniciarSession.setVisible(true);
        tabRegistrarU.setVisible(true);

    }//GEN-LAST:event_tabCerrarSessionActionPerformed

    private void tabIniciarSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabIniciarSessionActionPerformed

        inicioSession.setVisible(true);

    }//GEN-LAST:event_tabIniciarSessionActionPerformed

    private void tabListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabListarActionPerformed

        listarUsuario.setVisible(true);
    }//GEN-LAST:event_tabListarActionPerformed

    private void tabMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabMenuUsuarioActionPerformed

        menuUsuario.setVisible(true);
        
    }//GEN-LAST:event_tabMenuUsuarioActionPerformed

    private void tabMenuTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabMenuTelefonoActionPerformed

        menuTelefono.setVisible(true);
    }//GEN-LAST:event_tabMenuTelefonoActionPerformed

    private void tabIdiomaEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabIdiomaEsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabIdiomaEsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem tabCerrarSession;
    private javax.swing.JMenuItem tabIdiomaEN;
    private javax.swing.JMenuItem tabIdiomaEs;
    private javax.swing.JMenu tabIdiomas;
    private javax.swing.JMenuItem tabIniciarSession;
    private javax.swing.JMenu tabInicio;
    private javax.swing.JMenuItem tabListar;
    private javax.swing.JMenu tabMenu;
    private javax.swing.JMenuItem tabMenuTelefono;
    private javax.swing.JMenuItem tabMenuUsuario;
    private javax.swing.JMenuItem tabRegistrarU;
    // End of variables declaration//GEN-END:variables

}
